services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis-server:
    container_name: redis-server
    command: redis-server
    image: redis
    networks:
      - default

    
  django:
    container_name: django
    build: ./Django
    # command: bash -c "python manage.py makemigrations Auth && python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    command: bash -c "python manage.py makemigrations Auth Chat Game Notification WebApp && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Django/Code/:/code/
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - db
      - redis-server
    restart: always
    networks:
      - default

  web:
    container_name: Nginx
    build: ./Nginx
    ports:
      # - 443:443
      # - 80:443
      - 3000:443
      - 65535:443
    restart: always
    volumes:
      - ./Django/Code/static/:/static/
      - ./Django/Code/media/:/media/
    networks:
      - default
    depends_on:
      - django
    
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - db
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
      
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin

volumes:
  static_volume:
  pgadmin:
  postgres_data:



networks:
  default:

