services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - default

  redis-server:
    container_name: redis-server
    command: redis-server
    image: redis
    ports:
      - 6379:6379
    networks:
      - default

  django:
    container_name: Django
    build: ./Django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Django/Code/:/code/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis-server
    networks:
      - default

  web:
    container_name: Nginx
    build: ./Nginx
    ports:
      - 443:443
    volumes:
      - ./Django/Code/static/:/static/
      - ./Django/Code/media/:/media/
    networks:
      - default
    depends_on:
      - django
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin

volumes:
  static_volume:



networks:
  default:

