services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ../Db/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - default
  backend:
    container_name: backend
    build: ../backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend/Server:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - default
  web:
    container_name: web
    build:
      context: ../frontend
    volumes:
      - ../frontend/Code:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: ["sh", "-c", "npm run dev"]
    networks:
      - default
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - ../Db/pgadmin:/root/.pgadmin
      - ../Db/pgdata:/var/lib/postgresql/data
      - ../Db/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin

volumes:
  static_volume:



networks:
  default:

