# Generated by Django 4.2.13 on 2024-06-12 17:14

import Sockets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(default='Default', max_length=1000000)),
                ('players', models.JSONField(default=list)),
                ('ball', models.JSONField(default=Sockets.models.get_default_ball)),
                ('gameStatus', models.CharField(default='waiting', max_length=100)),
                ('roomMaxPlayers', models.IntegerField(default=2)),
                ('spectatorsMax', models.IntegerField(default=100)),
                ('spectators', models.JSONField(default=list)),
            ],
        ),
    ]
