# Generated by Django 4.2.13 on 2024-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='playerCount',
            field=models.IntegerField(default=0),
        ),
    ]
