# Generated by Django 4.2.13 on 2024-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sockets', '0003_room_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='playerCount',
            new_name='paddlesCount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.AddField(
            model_name='room',
            name='paddles',
            field=models.JSONField(default=dict),
        ),
    ]
