# Generated by Django 4.2.13 on 2024-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='walletCoins',
            field=models.IntegerField(default=0),
        ),
    ]
