# Generated by Django 4.2.13 on 2024-06-12 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_serverlogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friendlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
