# Generated by Django 4.2.13 on 2024-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_myuser_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='darkMode',
            field=models.BooleanField(default=False),
        ),
    ]
