# Generated by Django 3.2.12 on 2024-06-08 12:16

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='Auth/defaultAssets/ProfilePicture.png', upload_to=Auth.models.upload_to),
        ),
    ]
