# Generated by Django 3.2.12 on 2024-06-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_serverlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlogs',
            name='mehod',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='serverlogs',
            name='path',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
